
export const data =[
    {
        "id": 1,
        "name":"Are you proud of being Belarusian?",
        "tiket":"I am Belarusian because my parents who gave me life and brought me up are Belarusian. And what if I were born in a different country on a different continent? In my opinion, a sense of pride in your country, a sense of belonging to a particular nation develops in a person with time. Therefore at my age, by the way I am 18, I can say quite positively, that I am proud to live in Belarus. The real treasure of Belarus is its wonderful nature. The country has hundreds of wild forests, rolling hills, green valleys, sweet­scented meadows and golden fields. Beloveshzkaya Pushcha is the only place where you can meet mighty European bison in the wild. Belarus is also famous for its clear lakes and ribbon­like rivers, that’s why it’s called a blue­eyed one. The resorts of lakes Naroch and Braslav are open all year round and let tourists experience the unforgettable peaceful atmosphere."
    },
    {
        "id":2,
        "name":"UNESCO World Heritage1 List ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":3,
        "name":"My ideal school ",
        "tiket":"My ideal secondary school is a safe haven1. It shouldn’t be a place you hate going to, but a place you enjoy attending. I believe it should be social, as well as educational experience. A school should always have a soul… there should always be laughter ringing through the corridors.(Angela, 15, Moscow). My ideal school is a school quite unlike any school we’ve heard of. This school consists of a large library and basic recreational facilities. There are no classrooms. The school is built on the idea of active learning. No student is forced to learn. (Tanya, 14, Rome). School is the mould2, which shapes our future. It’s where we spend most of our valuable time — childhood. Yet I know from firsthand experience that many aspects should be changed: the impersonal attitude of some teachers who do everything only for results, instead of creating happy moments and valuable life experience for young people. These young people are far from being an ‘empty pot’ who are ready to be filled with knowledge. They are simply locked boxes full of potential which should be discovered by caring and encouraging teachers. (Anna, 15, Riga). Schools may be getting good results but they are not helping the students as individuals. It seems to me that it’s the learner who should ask questions. Give us the freedom to ask questions and do help us to find answers. Don’t you see we learn more from our experience and when people trust and respect us? We learn from our mistakes as well. (Hero Joy, 14, Kent). I think differences make the world go around. Good teachers know it more than Maths rules. I think school must teach differences. And at the moment some schools are doing the opposite, trying to make everyone normal. (Kate, 13, London) .Schools should develop creativity and dreams. When schools teach people not to seek knowledge on their own, people become passive. Everybody has the right to be free and choose what to be and what not to be, schools do not give that option, they have a ‘well organised’ systematic life for you, in which you have to fit. (Luis, 15, Boston)"
    },
    {
        "id":4,
        "name":"Anna’s diary ",
        "tiket":"Writing in a diary is a really strange experience for someone like me. Not only because I’ve never written anything before, but also because it seems to me that later on neither I nor anyone else will be interested in the thoughts of a thirteen­year­old schoolgirl. Oh well, it doesn’t matter. I feel like writing, and I have an even greater need to get all kinds of things off my chest1. “Paper has more patience than people.” I thought of this saying on one of those days when I was feeling a little depressed and was sitting at home with my chin in my hands. I was bored and wondering whether to stay in or go out. I finally stayed where I was and decided to start a diary. Yes, paper does have more patience, and since I’m not planning to let anyone else read this notebook, unless I should ever find a real friend, it probably won’t make a bit of difference. Now I’m back to the point that prompted me to keep a diary in the first place: I don’t have a friend. Let me put it more clearly, since no one will believe that a thirteen­year­old girl is completely alone in the world. And I’m not. I have loving parents and a sixteen­year­old sister, and there are about thirty people I can call friends. I have a bunch of admirers who can’t keep their adoring eyes off me and who constantly try to catch a glimpse1 of me in the classroom. I have a family, loving aunts and a good home. No, on the surface I seem to have everything, except my one true friend. All I think about when I’m with friends is having a good time. I can’t bring myself to talk about anything but ordinary everyday things. We don’t seem to be able to get closer, and that’s a problem. Maybe it’s my fault that we don’t trust each other. In any case, that’s just how things are. That’s why I started the diary. To enhance3 the image of this long­awaited friend in my imagination, I don’t want to write only about facts, but I want the diary to be my friend, and I am going to call this friend Kitty."
    },
    {
        "id":5,
        "name":"Be kind and stay safe ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":6,
        "name":"Christmas Tree",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":7,
        "name":"The Condemned Room ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":8,
        "name":"Great grandad",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":9,
        "name":"AN INTERVIEW ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":10,
        "name":"What is a good family? ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":11,
        "name":"AMELIA ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":12,
        "name":"THE STRESS OF COMMUTING ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":13,
        "name":"World Heritage1 List ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":14,
        "name":"Video Blogger ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":15,
        "name":"MAKE YOUR HOME GREENER ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":16,
        "name":"MR WEMMICK’S “CASTLE”",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":17,
        "name":"MOTHER TERESA ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":18,
        "name":"The most mystique1 picture ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":19,
        "name":"ARE YOU READY TO BE INDEPENDENT? ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":20,
        "name":"Technology",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":21,
        "name":"From librarian to political reporter ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":22,
        "name":"UNESCO World Heritage1 List ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":23,
        "name":"WE ARE YOUNGER THAN WE EVER WERE ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":24,
        "name":"Mi Luna",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":25,
        "name":"QUALITY OF COMMUNICATION",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":26,
        "name":"UNESCO World Heritage1 List ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":27,
        "name":"UNESCO World Heritage1 List ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":28,
        "name":"UNESCO World Heritage1 List ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    },
    {
        "id":29,
        "name":"Last tiket ",
        "tiket":"Belarus joined UNESCO in 1954. During many years, Belarus has been building up fruitful and dynamic relations with international organizations. Belarus programme of UNESCO activities includes numerous interesting projects in the fields of education, science, information, communications, and, of course, culture. In October 1988, Belarus joined the Convention on the Protection of theWorld Cultural and Natural Heritage. Today 4 Belarus sites have already been included into theUNESCO World Heritage List.    In 1992, theBelovezhskaya PushchaNational Park, a natural heritage object and a unique European forest reserve which has been protected since the 14th century, was the first one to become a UNESCO World Heritage Site. In 2000, the Mir Castle Complex, which was built at the beginning of the 16th century, was also added to the UNESCO World Heritage List. The successful combination of Gothic, Baroque and Renaissance architecture2 makesMir Castle one of Europe’s most impressive castles. In 2005, two more sites were included into the UNESCO World Heritage List. They are theArchitectural, Residential and Cultural Complex of the Radziwills in Nesvizhand theStruve Geodetic Arcpoints3.For centuries theNesvizh Palaceused to be the residence of the Radziwills, one of the richest families in Europe. Today the National Historical and Cultural Museum­Reserve Nesvizh is a wonderfully restored castle, which is visited by hundreds of tourists from all parts of the world. No wonder, it has become a landmark of Belarus."
    }
    ]